export interface Course {
    id: number;
    language: string;
    level: string;
    type: string;
    availability: string;
    image: string;
    link: string;
    badge: string;  
    title: string;  
    description: string; 
  }
  
  const courses: Course[] = [
    {
      id: 1,
      language: 'english',
      level: 'beginner',
      type: 'on-site',
      availability: 'open',
      image: 'https://i.ibb.co/jZy2Pfx/Photo-younes-Anglais-copy.jpg',
      link: "/course/1",
      badge: 'training_badge1site',
      title: 'training_title1',
      description: 'training_desc1',
    },
    {
      id: 2,
      language: 'english',
      level: 'intermediate',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/5MMpms9/and-then-when-it-comes.jpg',
      link: "/course/2",
      badge: 'training_badge2',
      title: 'training_title2',
      description: 'training_desc2',
    },
    {
      id: 3,
      language: 'english',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/LNPrr8v/PHOTO-BADIS-MAIN-PAGE.jpg',
      link: "/course/6",
      badge: 'training_badge1',
      title: 'training_title2',
      description: 'training_desc6',
    },
    {
      id: 4,
      language: 'english',
      level: 'advanced',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/W4vSKmGy/c1-C2.jpg',
      link: "/course",
      badge: 'training_badge3',
      title: 'training_title2',
      description: 'training_desc12',
    },
    {
      id: 5,
      language: 'english',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/jHZJy1X/ENGLISH-KIDS-MAIN.jpg',
      link: "/course",
      badge: 'training_badgekid',
      title: 'training_title2kid',
      description: 'training_desckid',
    },
    {
      id: 6,
      language: 'german',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/9nNZGR0/highest-quality-1.jpg',
      link: "/course/3",
      badge: 'training_badge1',
      title: 'training_title3',
      description: 'training_desc3',
    },
    {
      id: 7,
      language: 'french',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/khnYRCt/sdlmqjfmlkjsdf.jpg',
      link: "/course/4",
      badge: 'training_badge4',
      title: 'training_title4',
      description: 'training_desc4',
    },
    {
      id: 8,
      language: 'french',
      level: 'intermediate',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/3d8qyQd/FRENCH-IMAGE.jpg',
      link: "/course/french-b",
      badge: 'training_badge2',
      title: 'training_title4',
      description: 'training_desc4int',
    },
         {
      id: 17,
      language: 'french',
      level: 'advanced',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/QFRqbRQ5/NADA.jpg',
      link: "/course/french-C1-C2",
      badge: 'training_badge3',
      title: 'training_title4',
      description: 'training_desc4adv',
    },
    {
      id: 9,
      language: 'french',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/44SDJND/SPEAKING-FRENCH.jpg',
      link: "/course/french-spe",
      badge: 'training_badge1',
      title: 'training_title2spefr',
      description: 'training_desc2spefr',
    },
    {
      id: 16,
      language: 'french',
      level: 'intermediate',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/db2Pbsp/MAROUA-B1-B2.jpg',
      link: "/course/french-spe",
      badge: 'training_badge2',
      title: 'training_title2spefr',
      description: 'training_desc2spefr',
    },
    {
      id: 10,
      language: 'spanish',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/4mqWmRP/DSMQLJFMLSKJDFLKJSDF.jpg',
      link: "/course/5",
      badge: 'training_badge1',
      title: 'training_title5',
      description: 'training_desc5',
    },
    {
      id: 11,
      language: 'chinese',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/L9dCQJ1/PHOTO-CHINOIS.jpg',
      link: "/course/chinese",
      badge: 'training_badge1',
      title: 'training_title7',
      description: 'training_desc7',
    },
    {
      id: 12,
      language: 'italian',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/KxNmpDD/dslmkjfljksdf.jpg',
      link: "/course/8",
      badge: 'training_badge1',
      title: 'training_title8',
      description: 'training_desc8',
    },
    {
      id: 13,
      language: 'korean',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/Qv8MVF1/KOREAN-PICTURE-1.jpg',
      link: "/course/korean",
      badge: 'training_badge1',
      title: 'training_title9',
      description: 'training_desc9',
    },
    {
      id: 14,
      language: 'japanese',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/Y3qRCJy/japanese-1.jpg',
      link: "/course/",
      badge: 'training_badge1',
      title: 'training_title10',
      description: 'training_desc10',
    },
    {
      id: 15,
      language: 'turkish',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/6H7GzZb/TURKISH.jpg',
      link: "/course/turkish",
      badge: 'training_badge1',
      title: 'training_title11',
      description: 'training_desc11',
    },
    {
      id: 16,
      language: 'russian',
      level: 'beginner',
      type: 'zoom',
      availability: 'closed',
      image: 'https://i.ibb.co/s1TVjYV/PHOTO-RUSSIAN-MAIN-PAGE.jpg',
      link: "/course/russian",
      badge: 'training_badge1',
      title: 'training_title11',
      description: 'training_desc11',
    }
    
  ];
  
  export default courses;
  
